// Generated by CoffeeScript 1.3.3
(function() {
  var dir, dirs, fs, jsonFiles, jsonObj, key, newDir, p, path, paths, stat, _i, _j, _len, _len1;

  path = require('path');

  fs = require('fs-extra');

  if (global.__fnoc != null) {
    module.exports = global.__fnoc;
  } else {
    dirs = ['./', './config', './conf'];
    jsonFiles = [];
    global.__fnoc = {};
    for (_i = 0, _len = dirs.length; _i < _len; _i++) {
      dir = dirs[_i];
      newDir = path.join(process.cwd(), dir);
      if (fs.existsSync(dir)) {
        paths = fs.readdirSync(newDir);
        for (_j = 0, _len1 = paths.length; _j < _len1; _j++) {
          p = paths[_j];
          p = path.join(newDir, p);
          stat = fs.lstatSync(p);
          if (path.extname(p) === '.json' && stat.isFile()) {
            jsonObj = null;
            try {
              jsonObj = JSON.parse(fs.readFileSync(p));
            } catch (error) {
              console.log(error);
              console.log("fnoc: JSON parse error on file " + p);
            }
            key = path.basename(p, '.json');
            global.__fnoc[key] = jsonObj;
          }
        }
      }
    }
    module.exports = global.__fnoc;
  }

}).call(this);
